[project]
name = "simple-ai-agent-practice"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "aiofiles>=25.1.0",
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "fastapi>=0.136.1",
    "langchain-ollama>=1.1.0",
    "langchain-text-splitters>=1.1.2",
    "langgraph>=1.1.10",
    "ollama>=0.6.2",
    "psycopg>=3.3.4",
    "psycopg2-binary>=2.9.12",
    "pydantic>=2.13.3",
    "pydantic-settings>=2.14.0",
    "qdrant-client>=1.17.1",
    "ruff>=0.15.12",
    "sentence-transformers>=5.4.1",
    "sqlalchemy>=2.0.49",
    "uvicorn>=0.46.0",
]

 [tool.ruff]
  line-length = 100
  indent-width = 4
  target-version = "py312"
  fix = true
  show-fixes = true
  unsafe-fixes = false

  # Не лезем в артефакты/вендор
 exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]


  [tool.ruff.lint]
  # База: ошибки/стиль/импорты/баги/упрощения/pyupgrade + quality
  select = [
    "E", "F",        # pycodestyle + pyflakes
    "W",             # warnings
    "I",             # isort
    "B",             # flake8-bugbear
    "UP",            # pyupgrade
    "SIM",           # simplify
    "C4",            # comprehensions
    "A",             # builtins shadowing
    "ASYNC",         # async best practices
    "PIE",           # misc improvements
    "RUF",           # ruff-specific
  ]

  # Часто осознанно игнорят вместе с formatter'ом или по практичности
  ignore = [
    "E501",   # line length: пусть форматтер решает
    "RUF001",
    "RUF003"
  ]

  # Если хочешь, чтобы ruff сам конвертил кавычки/трейлинг и т.п. — включи:
  # extend-select = ["COM"]  # flake8-commas (по желанию)

  [tool.ruff.lint.per-file-ignores]
  "tests/**.py" = ["S101"]  # если включишь security-правила (S), в тестах assert ок
  "src/routes.py" = ["B008"]

  [tool.ruff.format]
  quote-style = "double"
  indent-style = "space"
  line-ending = "auto"
  docstring-code-format = true

  [tool.ruff.lint.isort]
  combine-as-imports = true
  known-first-party = ["src"]
